### ISSUE TITLE
Readme emojis not visible in Ubuntu based distributions

### ISSUE THREAD

**Issue by dineshkhadka** [TheBikramLama/gmail-spam-filter#1]
Some emojis are not visible in Ubuntu. Please see the attached screenshot for reference:
![image](https://user-images.githubusercontent.com/4678264/75682873-3a4eb600-5cbe-11ea-81b8-176d075458cd.png)

![image](https://user-images.githubusercontent.com/4678264/75682726-01aedc80-5cbe-11ea-96df-ed0f83dc8b22.png)

**Comment by TheBikramLama** [comment]
Does this emoji: 👤 work?

**Comment by dineshkhadka** [comment]
> Does this emoji:  work?

It does. Everything looks good
